[package]
name = "ppverif_fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.6.4", features = ["boolean", "shortint", "integer", "x86_64"] }
rand = "0.8.5"
fhe = { git = "https://github.com/Fainabi/fhe.rs" }
fhe-traits = { git = "https://github.com/Fainabi/fhe.rs" }
fhe-math = { git = "https://github.com/Fainabi/fhe.rs" }
thiserror = "2.0.9"

[features]
debug = []

[[example]]
name = "demo"
path = "examples/demo.rs"

[[example]]
name = "mal_demo"
path = "examples/malicious_demo.rs"

[[example]]
name = "bfv_demo"
path = "examples/bfv_demo.rs"

[dev-dependencies]
criterion = { version = "0.5" }

[[bench]]
name = "semihonest"
harness = false

[[bench]]
name = "malclient"
harness = false
