[package]
name = "ppverif_fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.6.4", features = ["boolean", "shortint", "integer", "x86_64"] }
rand = "0.8.5"
# rand_chacha = "0.3.1"
concrete-fft = "0.4.1"
# concrete-csprng = "0.4.1"
# aligned-vec = "0.5.0"

[[example]]
name = "demo"
path = "examples/demo.rs"
