[package]
name = "ppverif_fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.6.4", features = ["boolean", "shortint", "integer", "x86_64"] }
rand = "0.8.5"
# rand_chacha = "0.3.1"
concrete-fft = "0.4.1"
# concrete-csprng = "0.4.1"
# concrete-ntt = "0.2.0"
aligned-vec = "0.5.0"
fhe = { version = "^0.1.0-beta.8", path = "C:/Users/ZPF/gits/fhe.rs/crates/fhe" }
fhe-traits = { version = "^0.1.0-beta.8", path = "C:/Users/ZPF/gits/fhe.rs/crates/fhe-traits" }
fhe-math = { version = "^0.1.0-beta.8", path = "C:/Users/ZPF/gits/fhe.rs/crates/fhe-math" }
thiserror = "2.0.9"

[features]
debug = []

[[example]]
name = "demo"
path = "examples/demo.rs"

[[example]]
name = "mal_demo"
path = "examples/mal_demo.rs"

[[example]]
name = "mal_demo2"
path = "examples/malicious_demo.rs"

[[example]]
name = "bfv_demo"
path = "examples/bfv_demo.rs"
